project:
  type: website
  render:
    - "setup.qmd"
    - "*.qmd"
    - "presentation/*.qmd"

website:
  title: "Reproducibility Curriculum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Follow along"
        href: 00-follow-along.qmd
      - auto: modules
      - auto: extras
      - section: "Sample syllabi"
        contents:
        - text: "Econ 7850 Cornell"
          href: sample-econ7850.qmd
        - text: "Predoc sequence"
          href: sample-predoc.qmd
        - href: sample-twoday.qmd
      - text: "Acknowledgements"
        href: acknowledgment.qmd
      
      
format: 
  html:
    scrollable: true
    code-overflow: wrap
    max-width: 1400px
    grid:
      sidebar-width: 350px